Be lazy about decoding local command data
- Remove `encoding` arg from `mirror_and_capture()`.
- Don't decode eagerly in `mirror_and_capture()`; add bytes to capture
  buffers instead
- Pass those buffers of bytes to `Result` instead of strings
- In `Result`, join and decode byte buffers on demand

In addition to possibly being more performant, this fixes an issue where
a chunk of bytes would be read and then decoding would fail because the
last byte(s) of the chunk represented an incomplete Unicode character,
resulting in an exception like this:

    UnicodeDecodeError: 'utf-8' codec can't decode bytes in position \
    1022-1023: unexpected end of data